name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: laravel
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        dependency-version: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
            path: ~/.composer/cache/files
            key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, dom, fileinfo, mysql, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Copy .env && Generate keys
        run: |
          cp .env.example .env
          php artisan key:generate
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: passw0rd

      - name: Run sample Migrations
        run: |
          php artisan migrate --force
          php artisan db:seed
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: passw0rd

      - name: Execute & Run tests
        run: php artisan test --parallel
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: passw0rd

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: app-logs
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/laravel-boilerplate.png?size=48
          SLACK_MESSAGE: 'App Platform test all good :rocket:'
          SLACK_TITLE: 'App Platform'
          SLACK_USERNAME: general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
